### ISSUE TITLE
Remove material-ui in favor of glamor or another flexible CSS framework

### ISSUE THREAD

**Issue by vutran** [vutran/react-jsonschema#1]
Don't want to force users to use Material UI.

**Comment by adnasa** [comment]
What do you see is the biggest benefit with glamor?
The reason I ask is I want to understand the decision on the benefits of writing css in js and why it is favored over css-modules, or just pure css for that matter.

**Comment by vutran** [comment]
Primarily, the syntax provided from glamor is really easy to read. I've tried CSS modules in the past which works well. CSS modules was great in the beginning but doesn't really allow for a component to be fully repurposed completely unless you bring along the CSS file. That is one of the key factors I believe for using CSS in JS.

There's plenty of other CSS in JS frameworks out there such as radium, and aphrodite but I prefer the cleaner solution provided by glamor.

**Comment by vutran** [comment]
Initial decoupling of `material-ui` is available on the `develop` branch.

I may strip material-ui overall from the form and maybe implement a theming API via [glamor](https://github.com/threepointone/glamor/blob/master/docs/themes.md). This will allow us to re-apply material-ui as a theme instead.
